#!/bin/sh
# Fill dist/homebrew/ouro.rb in from a release's SHA256SUMS and print the result.
#
# Digests are read out of the manifest, never typed: a formula whose sha256 was
# transcribed by hand is a formula that will one day refuse to install for a reason
# nobody can reproduce. Every one of the four triples must be present — a formula missing
# a platform is a formula that installs the wrong binary on it.
#
# This prints to stdout. It does not write into a tap, does not commit, and does not
# publish; the tap is a separate repository and putting the file there is a deliberate
# act. See docs/DISTRIBUTION.md.
#
# Usage:
#   scripts/homebrew-formula.sh <version> [SHA256SUMS] > ouro.rb
#
#   OURO_BASE_URL   where the assets are downloaded from. Required: the URL Homebrew
#                   fetches has to be the real one, and this repository has no default.
#   OURO_HOMEPAGE   the formula's homepage. Defaults to OURO_BASE_URL.
#   OURO_LICENSE    the formula's license field. Defaults to the repository's LICENSE
#                   file if its first line names one, else the placeholder.

set -eu

self=$(basename "$0")
here=$(cd "$(dirname "$0")" && pwd)

die() { printf '%s: %s\n' "$self" "$*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $self <version> [SHA256SUMS]"

VERSION=$1
SUMS=${2:-SHA256SUMS}
TEMPLATE="$here/../dist/homebrew/ouro.rb"

[ -f "$TEMPLATE" ] || die "no template at $TEMPLATE"
[ -f "$SUMS" ] || die "$SUMS does not exist; pass the path to a release's SHA256SUMS"

case $VERSION in
    v*) die "pass the version (0.2.0), not the tag (v0.2.0)" ;;
esac

BASE_URL=${OURO_BASE_URL:-}
[ -n "$BASE_URL" ] || die "set OURO_BASE_URL to the directory the release assets are served from"
BASE_URL=${BASE_URL%/}

HOMEPAGE=${OURO_HOMEPAGE:-$BASE_URL}

# This repository states no license, so by default the formula states none either. A
# `license` field invented here would be a legal claim made by a shell script.
LICENSE=${OURO_LICENSE:-}
if [ -z "$LICENSE" ] && [ -f "$here/../LICENSE" ]; then
    LICENSE=$(head -n 1 "$here/../LICENSE" | tr -d '\r')
fi

digest_for() {
    # digest_for <triple> — the one digest the manifest gives for this triple's asset.
    _triple=$1
    _asset="ouro-$VERSION-$_triple"

    _found=$(sed -n "s/^\([0-9a-fA-F]\{64\}\)[ *]*$_asset\$/\1/p" "$SUMS")

    [ -n "$_found" ] || die "$SUMS has no entry for $_asset"

    # A manifest that names one asset twice is ambiguous, and choosing is not this
    # script's business.
    if [ "$(printf '%s\n' "$_found" | wc -l | tr -d ' ')" != "1" ]; then
        die "$SUMS gives $_asset more than one digest; refusing to choose"
    fi

    printf '%s' "$_found" | tr 'A-Z' 'a-z'
}

AARCH64_DARWIN=$(digest_for aarch64-apple-darwin)
X86_64_DARWIN=$(digest_for x86_64-apple-darwin)
AARCH64_LINUX=$(digest_for aarch64-unknown-linux-gnu)
X86_64_LINUX=$(digest_for x86_64-unknown-linux-gnu)

# The template's own preamble explains that it is a template; the generated file is not
# one, so the marker line splits them and this header replaces it. Saying what the file
# was generated from is how the next person knows not to edit it in the tap.
cat <<HEADER > "$SUMS.formula.tmp.$$"
# typed: false
# frozen_string_literal: true

# GENERATED by scripts/homebrew-formula.sh from dist/homebrew/ouro.rb. Do not edit here;
# edit the template and regenerate, or the next release overwrites your change.
#
#   version   $VERSION
#   digests   read from $SUMS
#   assets    $BASE_URL
#
# Homebrew checks the sha256 below against what it downloads and refuses to install on a
# mismatch. That is a real check — the digest is in this tap and the binary is on the
# release host, so an attacker needs both. It is NOT the release-signature check that
# \`ouro update\` and scripts/install.sh do; Homebrew has no notion of one. A formula is
# as trustworthy as this tap's commit history, which is a weaker statement than "the
# Ouroboros release key signed this".
HEADER

# `|` as the sed delimiter because a URL is full of slashes; the placeholders are
# uppercase and unique so a partial substitution is visible rather than quietly producing
# a formula that half works.
sed -n '/^# ---8<---/,$p' "$TEMPLATE" | sed '1d' | sed \
    -e "s|OURO_SHA256_AARCH64_APPLE_DARWIN|$AARCH64_DARWIN|g" \
    -e "s|OURO_SHA256_X86_64_APPLE_DARWIN|$X86_64_DARWIN|g" \
    -e "s|OURO_SHA256_AARCH64_UNKNOWN_LINUX_GNU|$AARCH64_LINUX|g" \
    -e "s|OURO_SHA256_X86_64_UNKNOWN_LINUX_GNU|$X86_64_LINUX|g" \
    -e "s|OURO_BASE_URL|$BASE_URL|g" \
    -e "s|OURO_HOMEPAGE|$HOMEPAGE|g" \
    -e "s|OURO_VERSION|$VERSION|g" \
    >> "$SUMS.formula.tmp.$$"

if [ -n "$LICENSE" ]; then
    sed -i.bak "s|OURO_LICENSE|$LICENSE|g" "$SUMS.formula.tmp.$$"
    rm -f "$SUMS.formula.tmp.$$.bak"
else
    printf '%s: no license is known (no LICENSE file, OURO_LICENSE unset); the formula states none.\n' "$self" >&2
    sed -i.bak '/^  license "OURO_LICENSE"$/d' "$SUMS.formula.tmp.$$"
    rm -f "$SUMS.formula.tmp.$$.bak"
fi

# Nothing may be left unfilled, in either direction: a half-substituted formula installs
# a URL that 404s or a digest that never matches, and both are found by a stranger.
if grep -n 'OURO_SHA256_\|OURO_VERSION\|OURO_BASE_URL\|OURO_LICENSE\|OURO_HOMEPAGE' "$SUMS.formula.tmp.$$" >/dev/null; then
    grep -n 'OURO_SHA256_\|OURO_VERSION\|OURO_BASE_URL\|OURO_LICENSE\|OURO_HOMEPAGE' "$SUMS.formula.tmp.$$" >&2
    rm -f "$SUMS.formula.tmp.$$"
    die "the template still has unfilled placeholders (listed above)"
fi

cat "$SUMS.formula.tmp.$$"
rm -f "$SUMS.formula.tmp.$$"
